### ISSUE TITLE
[page] Home

### ISSUE THREAD

**Issue by Th1nkK1D** [electinth/dream-constitution#16]
## Require
- #1 
- #2 
- #3 
- #4 

![image](https://user-images.githubusercontent.com/8860448/125780055-86bde047-bf3d-438c-ba85-4bbfe893820f.png)

**Comment by mixth** [comment]
Shall I move the current content of index to something like `catalog.tsx`?

**Comment by mixth** [comment]
Done.
The late `index.tsx` is retried to `catalog.tsx` and to be disposed in the future.
