### ISSUE TITLE
[component] How it work

### ISSUE THREAD

**Issue by Th1nkK1D** [electinth/dream-constitution#2]
![image](https://user-images.githubusercontent.com/8860448/125436183-ec35728f-f05e-4d38-8974-132b5ac3f115.png)

## Use in
- /
- /topics/[topicNumber]/

## Props
none

## Behavior
none

**Comment by mixth** [comment]
done with abd966e 8863f39

## Additional Note
It leave decisions of padding, background color, and width to the user. (Example shown in the `index.tsx`)
<img width="686" alt="Screen Shot 2021-07-24 at 2 12 29 PM" src="https://user-images.githubusercontent.com/6439183/126860983-f93ad55d-02c6-4bdd-b6d6-e52540247c2b.png">

## Result
### 360px
<img width="361" alt="Screen Shot 2021-07-24 at 2 12 07 PM" src="https://user-images.githubusercontent.com/6439183/126861037-23b3f76e-e130-4957-b5b2-ae013979b632.png">

### 544px
<img width="547" alt="Screen Shot 2021-07-24 at 2 11 55 PM" src="https://user-images.githubusercontent.com/6439183/126861040-05e9a392-6f0f-4ec2-a144-42e1b4436d03.png">
