### ISSUE TITLE
[enhancement] Home page

### ISSUE THREAD

**Issue by mixth** [electinth/dream-constitution#21]
## Wording on top
Waiting for more information from designer

## Wording on topic selection section
`มาร่วมออกแบบในประเด็นที่สำคัญในรัฐธรรมนูญ ลองเริ่มจากเรื่องที่คุณสนใจดูสิ` to `ออกแบบรัฐธรรมนูญไม่ยากอย่างที่คิด! ลองเริ่มต้นจากเรื่องที่คุณสนใจ`

## Insert text and image to 'Conlab คืออะไร' section
```
CONLAB - รัฐธรรมนูญก้าวหน้า คือใคร?

CONLAB - รัฐธรรมนูญก้าวหน้า คือ กลุ่มคนรุ่นใหม่จากหลากหลายวงการ ที่ต้องการผลักดันให้ประเทศไทยมีรัฐธรรมนูญที่ “ก้าวหน้า” เพื่อคุณภาพชีวิตที่ดีของประชาชน ก่อตั้งขึ้นในช่วงหลังการเลือกตั้งปี 2562

รัฐธรรมนูญที่ “ก้าวหน้า” ต้องยึดอยู่บน 3 หลักการเสมอ

1. 'เป็นกลางและเป็นธรรม' - สร้างกติกาที่เป็นที่ยอมรับของทุกฝ่ายในสังคม เปิดโอกาสให้ทุกกลุ่มความคิดสามารถรณรงค์-แข่งขัน ได้อย่างเท่าเทียมและอยู่ร่วมกันได้โดยไม่แตกแยก

2. 'สอดคล้องกับสากล' - มีเนื้อหาที่คุ้มครองสิทธิเสรีภาพของประชาชน และวางความสัมพันธ์ของโครงสร้างทางการเมืองต่างๆ ให้มีความสอดคล้องระหว่างอำนาจและที่มา

3. 'แก้ปัญหาที่อาจเกิดขึ้นในวันหน้า ตั้งแต่วันนี้' - ออกแบบโครงสร้างประเทศให้สามารถรับมือกับการเปลี่ยนแปลงที่รวดเร็วของโลกได้อย่างมีประสิทธิภาพ
```
with this image https://drive.google.com/file/d/1cCPK8yOaKfLhU2MGD6_KA1h7kmhRVeWh/view?usp=sharing  and its caption `(CONstitution LAB วันที่ 10 ธันวาคม 2562)`

**Comment by itwasup** [comment]
I've updated the design krub. 🙏
https://www.figma.com/file/A1mBypx3sqB0Xcy79YMOUl/DreamCon?node-id=242%3A947

**Comment by itwasup** [comment]
Background image for the hero section krub
<img width="800" alt="hero-bg" src="https://user-images.githubusercontent.com/32790592/130629489-a5f18fc1-75f0-4e24-9068-9fba10b082dd.png">
