### ISSUE TITLE
[data] Define data type

### ISSUE THREAD

**Issue by Th1nkK1D** [electinth/dream-constitution#5]
Define data type as a result of reshaping from google sheet

**Comment by mixth** [comment]
I propose `topic` as our smallest unit that can be kept in a JSON format. Since `option`, `answer` and `group` have no usage on its own, thus, they shall be used only as a form of properties for rendering component.

As showed below, I change `groups` in Google Sheets to `result` interface, hoping to make it less ambiguous. 

# Interfaces
### short-topics.json
```typescript
type ShortTopics = ShortTopic[];

interface ShortTopic {
  topicNumber: number;
  title: string;
  shortTitle: string;
  iconUrl: string;
  description: string;
}
````

### topic-{topicNumber}.json
`Topic` extends `ShortTopic` and holds all available information for a single topic.
```typescript
interface Topic extends ShortTopic {
  results: Result[]; // Describe in Google Sheets as 'groups'
  resultText: string; // Custom Markdown as discussed
  questions: Question[];
}
```


`Result` contains possible options for one addressed issue.

```typescript
interface Result {
  id: number;
  options: ResultOption[];
}

interface ResultOption {
  id: number;
  title: string;
  description: string; // Markdown
}
```

`Question` contains its answers and how it affects any result.

```typescript
interface Question {
  id: number;
  text: string;
  answers: Answer[];
}

interface Answer {
  id: number;
  text: string;
  effect: AnswerEffect;
}

interface AnswerEffect {
  resultId: number;
  resultOptionId: number;
  weight: number;
}
```

`AnswerEffect` tells a future calculator how the `Answer` favors the specific `Option` using `resultId` and `resultOptionId` and by how much `weight`. (As of now, this can be default as `1`)


# Example

### short-topics.json
```json
[
    {
        "topicNumber": 1,
        "title": "ออกแบบรัฐสภาไทย",
        "shortTitle": "รัฐสภา",
        "iconUrl": "https://",
        "description": "จะมาจากไหนบ้าง ต้องเลือกอย่างไร ทำอะไรได้บ้าง แบบไหนดี มาช่วยกันเลือกได้เลย"
    }
]
```
### topic-1.json
```json
{
    "topicNumber": 1,
    "title": "ออกแบบรัฐสภาไทย",
    "shortTitle": "รัฐสภา",
    "iconUrl": "https://",
    "description": "จะมาจากไหนบ้าง ต้องเลือกอย่างไร ทำอะไรได้บ้าง แบบไหนดี มาช่วยกันเลือกได้เลย",
    "resultText": "ประเทศไทยมีรัฐสภารูปแบบ `1` ประกอบไปด้วย",
    "results": [
        {
            "id": 1,
            "options": [
                {
                    "id": 1,
                    "title": "ระบบสภาเดี่ยว",
                    "description": "**ระบบสภาเดี่ยว** (Unicameral Legislature)"
                },
                {
                    "id": 2,
                    "title": "ระบบสภาคู่",
                    "description": "**ระบบสภาคู่** (Bicameral Legislature)"
                }
            ]
        }
    ],
    "questions": [
        {
            "id": 1,
            "text": "เห็นด้วยหรือไม่? ผู้แทนราษฎรต้องมาจากการเลือกตั้งโดยประชาชนเท่านั้น จึงจะทำหน้าที่ได้ดี",
            "answers": [
                {
                    "id": 1,
                    "text": "เห็นด้วย",
                    "effect": {
                        "resultId": 1,
                        "resultOptionId": 1,
                        "weight": 1
                    }
                },
                {
                    "id": 2,
                    "text": "ไม่ต้องมาจากการเลือกตั้งโดยประชาชนทั้งหมดก็ได้",
                    "effect": {
                        "resultId": 1,
                        "resultOptionId": 2,
                        "weight": 1
                    }
                }
            ]
        },
        {
            "id": 2,
            "text": "เห็นด้วยหรือไม่? ปัจจุบันนักการเมืองสามารถเป็นตัวแทนความหลากหลายของสังคมหรือเป็นผู้เชี่ยวชาญด้านต่าง ๆ อยู่แล้ว",
            "answers": [
                {
                    "id": 1,
                    "text": "เห็นด้วย",
                    "effect": {
                        "resultId": 1,
                        "resultOptionId": 1,
                        "weight": 1
                    }
                },
                {
                    "id": 2,
                    "text": "ไม่เห็นด้วย",
                    "effect": {
                        "resultId": 1,
                        "resultOptionId": 2,
                        "weight": 1
                    }
                }
            ]
        }
    ]
}
```
#

**Comment by Th1nkK1D** [comment]
@mixth SO FASTTTT! I agreed with most of the things but here is my opinion:

1. I'm not sure what is the benefit of having a short topic and a full topic when a short version is a subset of the full one? Feel like we keep redundant data.

2. Why you want to split each full topic into separate files? Do you plan to dynamically import only corresponded topic file on each topic route? (That's might relate to the first question as well) But since we doing a static site generator, we can combine into a single file and use `array.find` later on. Users shouldn't feel the performance cause it happened on built time.

3. I think we can get rid of weight. No plan to implement it. And if we need it in the future, just add it in the future. (I believe in YAGNI)

4. This one is not a strong opinion but I think we should add markdown to the key name ex: `descriptionMarkdown` or `descriptionMd` to prevent a confusion (My pain in the previous project haha)

The rest is looking great!

**Comment by mixth** [comment]
@Th1nkK1D I'm still not over the network-based API style. 😃 All seems legit. Let's go ahead with those.

**Comment by Th1nkK1D** [comment]
@mixth Thinking about creating type definition in the repo so others can import and use without the real data yet (will create an issue for data). Any idea how to achieve that nicely? (Not awkward to use with real data JSON when we have it)

**Comment by Th1nkK1D** [comment]
Defined data typed in 947c1de
The issue for fetching data is created #6
